
export const STATS = {
  // castle
  marksman: {
    name: 'Marksman',
    attack: 6,
    defense: 3,
    min_damage: 2,
    max_damage: 3,
    speed: 6,
    growth: 9,
    cost: 150,
    level: 2,
    value: 184,
    special: 'Shoots twice.',
  },
  griffin: {
    name: 'Griffin',
    attack: 8,
    defense: 8,
    min_damage: 3,
    max_damage: 6,
    health: 25,
    speed: 6,
    growth: 7,
    level: 3,
    value: 351,
    cost: 200,
    special: 'Two retaliations.',
  },
  royal_griffin: {
    name: 'Royal Griffin',
    attack: 9,
    defense: 9,
    min_damage: 3,
    max_damage: 6,
    health: 25,
    speed: 9,
    growth: 7,
    level: 3,
    value: 448,
    cost: 240,
    special: 'Unlimited retaliations.',
  },
  angel: {
    name: 'Angel',
    level: 7,
    attack: 20,
    defense: 20,
    min_damage: 50,
    max_damage: 50,
    health: 200,
    speed: 12,
    growth: 1,
    value: 5019,
    cost: 3000,
    special: '',
  },
  // rampart
  grand_elf: {
    name: 'Grand Elf',
    level: 3,
    attack: 9,
    defense: 5,
    min_damage: 3,
    max_damage: 5,
    speed: 7,
    growth: 7,
    value: 331,
    cost: 225,
    special: 'Shoots twice.',
  },
  unicorn: {
    name: 'Unicorn',
    level: 6,
    attack: 15,
    defense: 14,
    min_damage: 18,
    max_damage: 22,
    health: 90,
    speed: 7,
    growth: 2,
    value: 1806,
    cost: 950,
    special: 'Blind 20%. Magic resistance aura 20%.',
  },
  green_dragon: {
    name: 'Green Dragon',
    level: 7,
    attack: 18,
    defense: 18,
    min_damage: 40,
    max_damage: 50,
    health: 180,
    speed: 10,
    growth: 1,
    value: 4872,
    cost: 2400,
    special: 'Breath attack. Resists spells up to level 3.',
  },
  // tower
  iron_golem: {
    name: 'Iron Golem',
    level: 3,
    attack: 9,
    defense: 10,
    min_damage: 4,
    max_damage: 5,
    health: 35,
    speed: 5,
    growth: 6,
    value: 412,
    cost: 200,
    special: 'Spell damage resistance 75%.',
  },
  giant: {
    name: 'Giant',
    level: 7,
    attack: 19,
    defense: 16,
    min_damage: 40,
    max_damage: 60,
    health: 150,
    speed: 7,
    growth: 1,
    value: 3718,
    cost: 2000,
    special: 'Immunity to mind spells.',
  },
  // inferno
  magog: {
    name: 'Magog',
    level: 2,
    attack: 7,
    defense: 4,
    min_damage: 2,
    max_damage: 4,
    health: 13,
    speed: 6,
    growth: 8,
    value: 240,
    cost: 175,
    special: 'Fireball attack.',
  },
  efreet_sultan: {
    name: 'Efreet Sultan',
    attack: 16,
    defense: 14,
    min_damage: 16,
    max_damage: 24,
    health: 90,
    speed: 13,
    growth: 2,
    level: 6,
    value: 1848,
    cost: 1100,
    special: 'Fire shield. Immune to fire. Hates genies.',
  },
  // necropolis
  skeleton: {
    name: 'Skeleton',
    level: 1,
    attack: 5,
    defense: 4,
    min_damage: 1,
    max_damage: 3,
    health: 6,
    speed: 4,
    growth: 12,
    value: 60,
    cost: 60,
    special: 'Undead.',
  },
  vampire_lord: {
    name: 'Vampire Lord',
    level: 4,
    attack: 10,
    defense: 10,
    min_damage: 5,
    max_damage: 8,
    health: 40,
    speed: 9,
    growth: 4,
    value: 783,
    cost: 500,
    special: 'No enemy retaliation. Life drain. Undead.',
  },
  lich: {
    name: 'Lich',
    level: 5,
    attack: 13,
    defense: 10,
    min_damage: 11,
    max_damage: 13,
    health: 30,
    speed: 6,
    growth: 3,
    value: 848,
    cost: 550,
    special: 'Undead. Death cloud. Shots: 12.',
  },
  dread_knight: {
    name: 'Dread Knight',
    level: 6,
    attack: 18,
    defense: 18,
    min_damage: 15,
    max_damage: 30,
    health: 120,
    speed: 9,
    growth: 2,
    value: 2382,
    cost: 1500,
    special: 'Curse. 20% to attack with double base damage. Undead.',
  },
  bone_dragon: {
    name: 'Bone Dragon',
    level: 7,
    attack: 19,
    defense: 17,
    min_damage: 25,
    max_damage: 50,
    health: 150,
    speed: 9,
    growth: 1,
    value: 3388,
    cost: 1800,
    special: 'Undead. Morale -1. Aging.',
  },
  // dungeon
  infernal_troglodyte: {
    name: 'Infernal Troglodyte',
    level: 1,
    attack: 5,
    defense: 4,
    min_damage: 1,
    max_damage: 3,
    health: 6,
    speed: 5,
    growth: 14,
    value: 84,
    cost: 65,
    special: 'Immune to blinding and petrification.'
  },
  minotaur_king: {
    name: 'Minotaur King',
    level: 5,
    attack: 15,
    defense: 15,
    min_damage: 12,
    max_damage: 20,
    health: 50,
    speed: 8,
    growth: 3,
    value: 1068,
    cost: 575,
    special: '',
  },
  // stronghold
  wolf_raider: {
    name: 'Wolf Raider',
    level: 2,
    attack: 8,
    defense: 5,
    min_damage: 3,
    max_damage: 4,
    health: 10,
    speed: 8,
    growth: 9,
    value: 203,
    cost: 140,
    special: 'Attacks twice.'
  },
  orc: {
    name: 'Orc',
    level: 3,
    attack: 8,
    defense: 4,
    min_damage: 2,
    max_damage: 5,
    speed: 4,
    growth: 7,
    value: 192,
    cost: 150,
    special: '',
  },
  roc: {
    name: 'Roc',
    level: 5,
    attack: 13,
    defense: 11,
    min_damage: 11,
    max_damage: 15,
    speed: 7,
    growth: 3,
    value: 1027,
    cost: 600,
    special: '',
  },
  thunderbird: {
    name: 'Thunderbird',
    level: 5,
    attack: 13,
    defense: 11,
    min_damage: 11,
    max_damage: 15,
    speed: 11,
    growth: 3,
    value: 1106,
    cost: 700,
    special: 'Lightning strike 20% with damage equal to 10x the number of thunderbirds.'
  },
  cyclops: {
    name: 'Cyclops',
    level: 6,
    attack: 15,
    defense: 12,
    min_damage: 16,
    max_damage: 20,
    speed: 6,
    growth: 2,
    cyclops: 1266,
    cost: 750,
    special: 'Can attack siege walls.',
  },
  // fortress
  gnoll_marauder: {
    name: 'Gnoll Marauder',
    level: 1,
    attack: 4,
    defense: 6,
    min_damage: 2,
    max_damage: 3,
    health: 6,
    speed: 5,
    growth: 12,
    value: 90,
    cost: 70,
    special: '',
  },
  lizard_warrior: {
    name: 'Lizard Warrior',
    level: 2,
    attack: 6,
    defense: 8,
    min_damage: 2,
    max_damage: 5,
    health: 15,
    speed: 5,
    growth: 9,
    value: 156,
    cost: 140,
    special: '',
  },
  dragon_fly: {
    name: 'Dragon Fly',
    level: 3,
    attack: 8,
    defense: 10,
    min_damage: 2,
    max_damage: 5,
    health: 20,
    speed: 13,
    growth: 8,
    value: 312,
    cost: 750,
    special: ''
  },
  wyvern: {
    name: 'Wyvern',
    level: 6,
    attack: 14,
    defense: 14,
    min_damage: 14,
    max_damage: 18,
    health: 70,
    speed: 7,
    growth: 2,
    value: 1350,
    cost: 800,
    special: '',
  },
  wyvern_monarch: {
    name: 'Wyvern Monarch',
    level: 6,
    attack: 14,
    defense: 14,
    min_damage: 18,
    max_damage: 22,
    health: 70,
    speed: 11,
    growth: 2,
    value: 1518,
    cost: 1100,
    special: 'Poisonous',
  },
  // conflux
  pixie: {
    name: 'Pixie',
    level: 1,
    attack: 2,
    defense: 2,
    min_damage: 1,
    max_damage: 2,
    health: 3,
    speed: 7,
    growth: 20,
    value: 55,
    cost: 25,
    special: '',
  },
  water_elemental: {
    name: 'Water Elemental',
    level: 3,
    attack: 8,
    defense: 10,
    min_damage: 3,
    max_damage: 7,
    health: 30,
    speed: 5,
    growth: 6,
    value: 315,
    cost: 300,
    special: 'Fire vulnerability.',
  },
  fire_elemental: {
    name: 'Fire Elemental',
    level: 4,
    attack: 10,
    defense: 8,
    min_damage: 4,
    max_damage: 6,
    health: 35,
    speed: 6,
    growth: 6,
    value: 345,
    cost: 350,
    special: '',
  },
  // cove
  nix_warrior: {
    name: 'Nix Warrior',
    level: 6,
    attack: 14,
    defense: 17,
    min_damage: 18,
    max_damage: 22,
    health: 90,
    speed: 7,
    growth: 2,
    value: 2116,
    cost: 1300,
    special: '60% of the Attack parameter is ignored when a creature attacks Nix.'
  },
  // neutral
  nomad: {
    name: 'Nomad',
    level: 3,
    attack: 9,
    defense: 8,
    min_damage: 2,
    max_damage: 6,
    health: 30,
    speed: 7,
    growth: 7,
    value: 345,
    cost: 200,
    special: 'Sandwalker.'
  }  ,
}

export const HEROES = {
  knight: {
    air_magic: 3,
    earth_magic: 2,
    fire_magic: 1,
    water_magic: 4,
    earth_lvl4: 0.20,
  },
  ranger: {
    air_magic: 1,
    earth_magic: 3,
    fire_magic: 0,
    water_magic: 3,
    earth_lvl4: 0.42,
  },
  demoniac: {
    air_magic: 2,
    earth_magic: 3,
    fire_magic: 4,
    water_magic: 1,
    earth_lvl4: 0.30,
  },
  death_knight: {
    air_magic: 2,
    earth_magic: 4,
    fire_magic: 1,
    water_magic: 3,
    earth_lvl4: 0.40,
  },
  overlord: {
    air_magic: 1,
    earth_magic: 3,
    fire_magic: 2,
    water_magic: 0,
    earth_lvl4: 0.50,
  },
  barbarian: {
    air_magic: 3,
    earth_magic: 3,
    fire_magic: 2,
    water_magic: 0,
    earth_lvl4: 0.38,
  },
  beastmaster: {
    air_magic: 1,
    earth_magic: 3,
    fire_magic: 0,
    water_magic: 2,
    earth_lvl4: 0.50,
  },
  planeswalker: {
    air_magic: 2,
    earth_magic: 3,
    fire_magic: 3,
    water_magic: 2,
    earth_lvl4: 0.30,
  },
  captain: {
    air_magic: 3,
    earth_magic: 4,
    fire_magic: 2,
    water_magic: 2,
    earth_lvl4: 0.36,
  },
};

export const TITLES = {
  additional_attack: 'Additional Attack',
  additional_defense: 'Additional Defense',
  amount: 'Amount',
  attack: 'Attack',
  attacking: 'Attacking',
  cost: 'Cost',
  defending: 'Defending',
  defense: 'Defense',
  growth: 'Growth',
  health: 'Health',
  level: 'Level',
  max_damage: 'Maximum Damage',
  min_damage: 'Minimum Damage',
  name: 'Name',
  speed: 'Speed',
  value: 'Value',
}

export const NAMES = {
  'Additional Attack': 'additional_attack',
  'Additional Defense': 'additional_defense',
  'Amount': 'amount',
  'Attack': 'attack',
  'Attacking': 'attacking',
  'Cost': 'cost',
  'Defending': 'defending',
  'Defense': 'defense',
  'Growth': 'growth',
  'Health': 'health',
  'Level': 'level',
  'Maximum Damage': 'max_damage',
  'Minimum Damage': 'min_damage',
  'Name': 'name',
  'Speed': 'speed',
  'Value': 'value',
};


const data = {
  HEROES: HEROES,
  NAMES: NAMES,
  STATS: STATS,
  TITLES: TITLES,
};

export default data;
